/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schemaXX = configure({
    database: {
        identifier: "ID66zoOWQbVui2ztRVXVdJgQ",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        sslCert: secret("SUPABASE_CA_CERT")
    }
}).schema({
 "tblUser": a.model({
        id: a.integer().default(),
        awsId: a.string(),
        firstName: a.string().required(),
        lastName: a.string().required(),
        email: a.string().required(),
        userRole: a.string().required(),
        active: a.boolean(),
        deleted: a.boolean(),
        createdAt: a.datetime(),
        updatedAt: a.datetime(),
        createdBy: a.integer(),
        updatedBy: a.integer(),
        phone: a.string(),
        timezone: a.string(),
        creator: a.belongsTo('tblUser', 'createdBy'),
        editor: a.belongsTo('tblUser', 'updatedBy'),
    }).identifier([
        "id"
    ]),
});
